#!/usr/bin/env python3
"""Prepare Building3D style assets for the web viewer.

The raw data uses absolute UTM coordinates (x around 5.4e5, y around 6.6e6).
Three.js stores positions as float32, where a magnitude of 6.6e6 has a spacing
of roughly 0.5 m, so the geometry collapses if the raw values are used directly.
This script subtracts one shared origin from the point cloud and from every
wireframe of the same building, keeping them perfectly aligned while bringing
the magnitudes down to a few tens of meters.

Point cloud input is the Building3D text format, whitespace separated.
  x y z r g b [intensity ...]
Wireframe input is an OBJ holding only "v" and "l" records.

A building can carry several wireframes, for instance our own reconstruction
next to a baseline. They must share one origin or they would no longer overlap,
so they are converted together in a single run.

Usage
  python3 tools/prepare_models.py --txt 7114.txt --out-dir static/models \
      --name b7114 --wf wf=7114_origin.obj --wf bw=7114_200.obj

Outputs <name>_pc.ply (binary little endian, xyz plus rgb) and one
<name>_<key>.obj per wireframe, where the key matches the key the viewer reads
from data-items. The origin is written into every file as a comment so the
mapping back to the original coordinates is never lost.
"""

import argparse
import os
import struct


def read_points(path):
    pts = []
    with open(path) as fh:
        for line in fh:
            parts = line.split()
            if len(parts) < 3:
                continue
            x, y, z = float(parts[0]), float(parts[1]), float(parts[2])
            if len(parts) >= 6:
                r, g, b = (int(round(float(parts[i]))) for i in (3, 4, 5))
            else:
                r = g = b = 200
            pts.append((x, y, z, max(0, min(255, r)), max(0, min(255, g)), max(0, min(255, b))))
    return pts


def read_obj(path):
    verts, edges = [], []
    with open(path) as fh:
        for line in fh:
            parts = line.split()
            if not parts:
                continue
            if parts[0] == 'v':
                verts.append(tuple(float(v) for v in parts[1:4]))
            elif parts[0] == 'l':
                idx = [int(p.split('/')[0]) for p in parts[1:]]
                # An l record may chain more than two vertices, so split it into pairs.
                for a, b in zip(idx, idx[1:]):
                    edges.append((a, b))
            elif parts[0] == 'f':
                idx = [int(p.split('/')[0]) for p in parts[1:]]
                for k in range(len(idx)):
                    edges.append((idx[k], idx[(k + 1) % len(idx)]))
    return verts, edges


def compute_origin(clouds):
    """One origin for every cloud of vertices belonging to the same building."""
    xs, ys, zs = [], [], []
    for c in clouds:
        for v in c:
            xs.append(v[0]); ys.append(v[1]); zs.append(v[2])
    # Centre in the ground plane, and put the lowest point at zero height.
    return ((min(xs) + max(xs)) / 2.0, (min(ys) + max(ys)) / 2.0, min(zs))


def write_ply(path, points, origin):
    ox, oy, oz = origin
    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment generated by prepare_models.py\n"
        "comment origin %.6f %.6f %.6f\n"
        "element vertex %d\n"
        "property float x\nproperty float y\nproperty float z\n"
        "property uchar red\nproperty uchar green\nproperty uchar blue\n"
        "end_header\n" % (ox, oy, oz, len(points))
    )
    with open(path, 'wb') as fh:
        fh.write(header.encode('ascii'))
        pack = struct.Struct('<fffBBB').pack
        for x, y, z, r, g, b in points:
            fh.write(pack(x - ox, y - oy, z - oz, r, g, b))


def write_obj(path, verts, edges, origin):
    ox, oy, oz = origin
    with open(path, 'w') as fh:
        fh.write("# generated by prepare_models.py\n")
        fh.write("# origin %.6f %.6f %.6f\n" % (ox, oy, oz))
        for x, y, z in verts:
            fh.write("v %.6f %.6f %.6f\n" % (x - ox, y - oy, z - oz))
        for a, b in edges:
            fh.write("l %d %d\n" % (a, b))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--txt', required=True, help='point cloud in Building3D text format')
    ap.add_argument('--wf', action='append', default=[], metavar='KEY=PATH',
                    help='wireframe OBJ, named by the key the viewer reads, repeatable')
    ap.add_argument('--obj', help='shorthand for --wf wf=PATH')
    ap.add_argument('--out-dir', required=True)
    ap.add_argument('--name', required=True, help='output basename, e.g. b7114')
    args = ap.parse_args()

    wires = []
    if args.obj:
        wires.append(('wf', args.obj))
    for entry in args.wf:
        if '=' not in entry:
            ap.error('--wf expects KEY=PATH, got ' + entry)
        key, path = entry.split('=', 1)
        wires.append((key, path))
    if not wires:
        ap.error('at least one wireframe is required, via --wf or --obj')

    points = read_points(args.txt)
    parsed = [(key, read_obj(path)) for key, path in wires]
    origin = compute_origin([points] + [v for _, (v, _) in parsed])

    os.makedirs(args.out_dir, exist_ok=True)
    ply_path = os.path.join(args.out_dir, args.name + '_pc.ply')
    write_ply(ply_path, points, origin)

    xs = [p[0] - origin[0] for p in points]
    ys = [p[1] - origin[1] for p in points]
    zs = [p[2] - origin[2] for p in points]
    print("origin   %.3f %.3f %.3f" % origin)
    print("points   %d -> %s (%.1f KB)" % (len(points), ply_path, os.path.getsize(ply_path) / 1024))
    for key, (verts, edges) in parsed:
        obj_path = os.path.join(args.out_dir, args.name + '_' + key + '.obj')
        write_obj(obj_path, verts, edges, origin)
        print("%-8s verts %d, edges %d -> %s (%.1f KB)" % (
            key, len(verts), len(edges), obj_path, os.path.getsize(obj_path) / 1024))
    print("extent   x %.2f  y %.2f  z %.2f (metres, z is up)" % (
        max(xs) - min(xs), max(ys) - min(ys), max(zs) - min(zs)))


if __name__ == '__main__':
    main()
